<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: service.proto

namespace App\GRPC\Demo;

use Spiral\GRPC;

interface DemoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "demo.DemoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Point $in
    * @return Feature
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetFeature(GRPC\ContextInterface $ctx, Point $in): Feature;
}
