<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\GRPC\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.Feature</code>
 */
class Feature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.demo.Point location = 2;</code>
     */
    private $location = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \App\GRPC\Demo\Point $location
     * }
     */
    public function __construct($data = NULL) {
        \App\GRPC\Metadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.demo.Point location = 2;</code>
     * @return \App\GRPC\Demo\Point
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.demo.Point location = 2;</code>
     * @param \App\GRPC\Demo\Point $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \App\GRPC\Demo\Point::class);
        $this->location = $var;

        return $this;
    }

}

