<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\GRPC\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.Point</code>
 */
class Point extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 latitude = 1;</code>
     */
    private $latitude = 0;
    /**
     * Generated from protobuf field <code>int32 longitude = 2;</code>
     */
    private $longitude = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $latitude
     *     @type int $longitude
     * }
     */
    public function __construct($data = NULL) {
        \App\GRPC\Metadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 latitude = 1;</code>
     * @return int
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>int32 latitude = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkInt32($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 longitude = 2;</code>
     * @return int
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>int32 longitude = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkInt32($var);
        $this->longitude = $var;

        return $this;
    }

}

