<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\GRPC\Metadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7010a0d736572766963652e70726f746f120464656d6f222c0a05506f" .
            "696e7412100a086c6174697475646518012001280512110a096c6f6e6769" .
            "7475646518022001280522360a0746656174757265120c0a046e616d6518" .
            "0120012809121d0a086c6f636174696f6e18022001280b320b2e64656d6f" .
            "2e506f696e7432390a0b44656d6f53657276696365122a0a0a4765744665" .
            "6174757265120b2e64656d6f2e506f696e741a0d2e64656d6f2e46656174" .
            "757265220042275a012eca020d4170705c475250435c44656d6fe2021141" .
            "70705c475250435c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

